language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

# jobs for ppc64le tests  
job:
  include:
    - arch: ppc64le
      python: 2.7
    - arch: ppc64le
      python: 3.8
    - arch: ppc64le
      python: 3.9-dev
      
# command to install dependencies
install: "pip install coverage coveralls"
# command to run tests
script: nosetests
after_success: coveralls
